#!/usr/bin/env python3
"""Export a complete fftgen core deliverable set (PLAN.md P5b).

Produces a self-contained directory for one configuration: RTL sources,
twiddle/preload artifacts, a GENERATED top-level wrapper with every
parameter baked in (no -G overrides needed anywhere), fft_params.vh,
human-readable params.txt / twiddle_map.txt, verification vectors
(stimulus + golden expected), and Vivado OOC scripts.

    python3 src/export_core.py --num-points 1024 --outdir build/export
    python3 src/export_core.py --num-points 8192 --ssr 2 \\
        --output-order native --outdir build/export_ssr

The exported tree is verified with the same bit-exact flow as the test
suite (see README.txt written alongside the files).
"""

import argparse
import os
import shutil
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))

from config import FFTConfig

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RTL = os.path.join(ROOT, "rtl")
TB = os.path.join(ROOT, "tb")

# memory-style cutoffs (doc/mem_cutoffs.md S3); mirrored from fft_stage
LUTRAM_MAX_BITS = 1024
BRAM_MAX_BITS = 262144


# ----------------------------------------------------------------------
# config helpers
# ----------------------------------------------------------------------

def build_config(args) -> FFTConfig:
    scaling = args.scaling
    if scaling != "auto":
        scaling = [int(x) for x in scaling.replace(",", " ").split()]
    return FFTConfig(
        num_points=args.num_points,
        inverse=args.inverse,
        ssr=args.ssr,
        input_order=args.input_order,
        output_order=args.output_order,
        sample_width=args.sample_width,
        sample_decimal=args.sample_decimal,
        output_width=args.output_width,
        output_decimal=args.output_decimal,
        twiddle_width=args.twiddle_width,
        scaling=scaling,
    )


def lane_cfg(cfg: FFTConfig) -> FFTConfig:
    """Per-lane engine config for SSR (M-point R=1 engine)."""
    import copy
    lc = copy.copy(cfg)
    lc.num_points = cfg.num_points // cfg.ssr
    lc.ssr = 1
    return lc


def intern_width(cfg: FFTConfig) -> int:
    return cfg.sample_width + max(0, cfg.num_stages - sum(cfg.shifts)) + 1


def scaling_pack(cfg: FFTConfig) -> int:
    pack = 0
    for s, sh in enumerate(cfg.shifts):
        pack |= (sh & 3) << (2 * s)
    return pack


def reorder_out(cfg: FFTConfig) -> bool:
    """Output reorder inserted when the outer order differs from the
    core's natural output order (bitreversed for DIF, native for DIT)."""
    core_out = "native" if cfg.is_dit else "bitreversed"
    return cfg.output_order != core_out


def mem_style_bits(bits: int) -> str:
    if bits <= LUTRAM_MAX_BITS:
        return "distributed"
    if bits < BRAM_MAX_BITS:
        return "block"
    return "ultra"


def core_files(cfg: FFTConfig):
    """RTL source files for this architecture (fft_core.v first so the
    preload define is parsed before fft_sdf.v in naive compile orders)."""
    if cfg.ssr > 1:
        return ["fft_ssr.v", "fft_top.v", "fft_sdf.v", "fft_reorder.v",
                "fft_cross.v"]
    return ["fft_sdf.v", "fft_reorder.v"]


def latency_cycles(cfg: FFTConfig) -> int:
    """Declared streaming latency in enabled cycles (from the golden
    models -- single source of truth)."""
    from golden import OrderedFFTModel
    if cfg.ssr > 1:
        from golden_ssr import SSRGoldenModel
        return SSRGoldenModel(cfg).latency
    import dataclasses
    nat_in, nat_out = (("bitreversed", "native") if cfg.is_dit
                       else ("native", "bitreversed"))
    core = SDFGoldenModel_latent(dataclasses.replace(
        cfg, input_order=nat_in, output_order=nat_out), dit=cfg.is_dit)
    lat = core.latency
    if reorder_out(cfg):
        lat += cfg.num_points          # ping-pong reorder depth
    return lat


def SDFGoldenModel_latent(cfg, dit):
    from golden import SDFGoldenModel
    return SDFGoldenModel(cfg, dit=dit)


# ----------------------------------------------------------------------
# fft_params.vh
# ----------------------------------------------------------------------

def engine_cfg(cfg: FFTConfig) -> FFTConfig:
    """The config whose per-stage schedule feeds the RTL generics: the
    M-point lane engine for SSR, the transform itself for R=1."""
    return lane_cfg(cfg) if cfg.ssr > 1 else cfg


def params_header(cfg: FFTConfig) -> str:
    eng = engine_cfg(cfg)
    pack = scaling_pack(eng)
    lines = [
        "// fft_params.vh -- concrete parameters for this FFT build",
        "// (generated by src/export_core.py -- do not edit).",
        "//",
        "// Nothing includes this file automatically; it documents the build",
        "// and can be used by surrounding logic. The generated fft_core.v",
        "// (R=1) bakes the same values into the fft_top instantiation.",
        "",
        "// architecture",
        f"`define FFT_NUM_POINTS      {cfg.num_points}",
        f"`define FFT_SSR             {cfg.ssr}",
        f"`define FFT_INVERSE         {1 if cfg.inverse else 0}",
        f"`define FFT_INPUT_ORDER     \"{cfg.input_order}\"",
        f"`define FFT_OUTPUT_ORDER    \"{cfg.output_order}\"",
        f"`define FFT_TOPOLOGY        {1 if cfg.is_dit else 0}      // 0=DIF 1=DIT",
        f"`define FFT_REORDER_OUT     {1 if reorder_out(cfg) else 0}",
        f"`define FFT_NUM_STAGES      {cfg.num_stages}",
        f"`define FFT_PIPE_DEPTH      10     // NLAYERS (golden _SDFStage)",
        "",
        "// widths / quantization",
        f"`define FFT_SAMPLE_WIDTH    {cfg.sample_width}",
        f"`define FFT_SAMPLE_DECIMAL  {cfg.sample_decimal}",
        f"`define FFT_OUTPUT_WIDTH    {cfg.output_width}",
        f"`define FFT_OUTPUT_DECIMAL  {cfg.output_decimal}",
        f"`define FFT_TWIDDLE_WIDTH   {cfg.twiddle_width}",
        f"`define FFT_TWIDDLE_DECIMAL {cfg.twiddle_decimal}",
        f"`define FFT_SCALING_PACK    32'h{pack:08x}  "
            "// 2 bits/stage, stage 0 in LSBs"
            + (" (per-lane engine)" if cfg.ssr > 1 else ""),
        f"`define FFT_INTERN_WIDTH    {intern_width(eng)}",
        "",
        "// scaling schedule (per stage)",
    ]
    for s, sh in enumerate(cfg.shifts):
        lines.append(f"//   stage {s:2d}: shift {sh}")
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------------
# generated fft_core.v (R=1): fft_top module with baked parameters
# ----------------------------------------------------------------------

def _replace_many(text, subs):
    for k, v in subs.items():
        text = text.replace(k, v)
    return text.splitlines()


def core_wrapper_r1(cfg: FFTConfig) -> str:
    """Generated replacement for rtl/fft_top.v with every parameter baked.

    Module name stays fft_top so the shipped testbench and any IP-style
    integration see the same interface as the repository wrapper. Only
    valid for ssr == 1 (the SSR top keeps its generics; see params.txt).
    """
    assert cfg.ssr == 1
    ro = reorder_out(cfg)
    iw = intern_width(cfg)
    pack = scaling_pack(cfg)

    def sdf_inst(indent="        "):
        return "\n".join([
            f"{indent}fft_sdf #(",
            f"{indent}    .NUM_POINTS     ({cfg.num_points}),",
            f"{indent}    .SAMPLE_WIDTH   ({cfg.sample_width}),",
            f"{indent}    .SAMPLE_DECIMAL ({cfg.sample_decimal}),",
            f"{indent}    .OUTPUT_WIDTH   ({cfg.output_width}),",
            f"{indent}    .OUTPUT_DECIMAL ({cfg.output_decimal}),",
            f"{indent}    .TWIDDLE_WIDTH  ({cfg.twiddle_width}),",
            f"{indent}    .TWIDDLE_DECIMAL({cfg.twiddle_decimal}),",
            f"{indent}    .SCALING_PACK   (32'h{pack:08x}),",
            f"{indent}    .TOPOLOGY       ({1 if cfg.is_dit else 0}),",
            f"{indent}    .TWIDDLE_FILE   (\"fft_twiddles.mem\"),",
            f"{indent}    .INTERN_WIDTH   ({iw}),",
            f"{indent}    .PIPE_DEPTH     (10)",
            f"{indent}) u_core (",
            f"{indent}    .clk            (clk),",
            f"{indent}    .ce             (ce),",
            f"{indent}    .s_axis_tvalid  (s_axis_tvalid),",
            f"{indent}    .s_axis_tdata_re(s_axis_tdata_re),",
            f"{indent}    .s_axis_tdata_im(s_axis_tdata_im),",
            f"{indent}    .s_axis_tuser   (s_axis_tuser),",
            f"{indent}    .s_axis_tlast   (s_axis_tlast),",
            f"{indent}    .m_axis_tvalid  (core_valid),",
            f"{indent}    .m_axis_tdata_re(core_re),",
            f"{indent}    .m_axis_tdata_im(core_im),",
            f"{indent}    .m_axis_tuser   (core_user),",
            f"{indent}    .m_axis_tlast   (core_last),",
            f"{indent}    .rst            (rst)",
            f"{indent});",
        ])

    if ro:
        body = "\n".join([
            "    wire        core_valid;",
            "    wire signed [INTERN_WIDTH-1:0] core_re, core_im;",
            "    wire        core_user, core_last;",
            "",
            sdf_inst(),
            "",
            "    fft_reorder #(",
            f"        .NUM_POINTS ({cfg.num_points}),",
            f"        .WIDTH      ({cfg.output_width})",
            "    ) u_reorder (",
            "        .clk            (clk),",
            "        .ce             (ce),",
            "        .s_axis_tvalid  (core_valid),",
            "        .s_axis_tdata_re(core_re),",
            "        .s_axis_tdata_im(core_im),",
            "        .s_axis_tuser   (core_user),",
            "        .s_axis_tlast   (core_last),",
            "        .m_axis_tvalid  (m_axis_tvalid),",
            "        .m_axis_tdata_re(m_axis_tdata_re),",
            "        .m_axis_tdata_im(m_axis_tdata_im),",
            "        .m_axis_tuser   (m_axis_tuser),",
            "        .m_axis_tlast   (m_axis_tlast),",
            "        .rst            (rst)",
            "    );",
        ])
    else:
        # direct connection: core outputs ARE the module outputs
        direct = {"core_valid": "m_axis_tvalid",
                  "(core_re)": "(m_axis_tdata_re)",
                  "(core_im)": "(m_axis_tdata_im)",
                  "core_user": "m_axis_tuser",
                  "core_last": "m_axis_tlast"}
        body = "\n".join(line for line in
                         _replace_many(sdf_inst(), direct))

    return "\n".join([
        "// fft_core.v -- GENERATED by src/export_core.py; do not edit.",
        "// Regenerate with:",
        "//   python3 src/export_core.py ... --outdir <this directory>",
        "//",
        "// fft_top module with this build's concrete parameters baked in",
        f"// ({cfg.num_points}-point {'IFFT' if cfg.inverse else 'FFT'}, "
        f"{cfg.input_order}->{cfg.output_order}, "
        f"Q{cfg.sample_decimal} in / Q{cfg.output_decimal} out).",
        "//",
        "// NOTE: this file REPLACES the generic rtl/fft_top.v of the source",
        "// tree -- compile it together with fft_sdf.v/fft_reorder.v INSTEAD",
        "// of the repository wrapper.",
        "//",
        "// The preload pack below feeds fft_sdf's post-warm FSM state; the",
        "// include makes the define visible before fft_sdf.v is parsed",
        "// (keep this file first in the compile order).",
        "`include \"fft_preloads.vh\"",
        "",
        "`default_nettype none",
        "",
        "module fft_top #(",
        f"    parameter integer NUM_POINTS     = {cfg.num_points},",
        f"    parameter integer SAMPLE_WIDTH   = {cfg.sample_width},",
        f"    parameter integer SAMPLE_DECIMAL = {cfg.sample_decimal},",
        f"    parameter integer OUTPUT_WIDTH   = {cfg.output_width},",
        f"    parameter integer OUTPUT_DECIMAL = {cfg.output_decimal},",
        f"    parameter integer TWIDDLE_WIDTH  = {cfg.twiddle_width},",
        f"    parameter integer TWIDDLE_DECIMAL = {cfg.twiddle_decimal},",
        f"    parameter integer SCALING_PACK   = 32'h{pack:08x},",
        f"    parameter integer TOPOLOGY       = {1 if cfg.is_dit else 0},",
        f"    parameter integer REORDER_OUT    = {1 if ro else 0},",
        "    parameter TWIDDLE_FILE           = \"fft_twiddles.mem\",",
        f"    parameter integer INTERN_WIDTH   = {iw},",
        "    parameter integer PIPE_DEPTH     = 10",
        ")(",
        "    input  wire                        clk,",
        "    input  wire                        ce,",
        "    input  wire                        s_axis_tvalid,",
        f"    input  wire [SAMPLE_WIDTH-1:0]     s_axis_tdata_re,",
        f"    input  wire [SAMPLE_WIDTH-1:0]     s_axis_tdata_im,",
        "    input  wire                        s_axis_tuser,",
        "    input  wire                        s_axis_tlast,",
        "",
        "    output wire                        m_axis_tvalid,",
        "    output wire [OUTPUT_WIDTH-1:0]     m_axis_tdata_re,",
        "    output wire [OUTPUT_WIDTH-1:0]     m_axis_tdata_im,",
        "    output wire                        m_axis_tuser,",
        "    output wire                        m_axis_tlast,",
        f"    output wire [NUM_POINTS*INTERN_WIDTH-1:0] dbg_stage_re,",
        f"    output wire [NUM_POINTS*INTERN_WIDTH-1:0] dbg_stage_im,",
        "",
        "    input  wire                        rst",
        ");",
        "",
        "    localparam integer INTERN_WIDTH_L = INTERN_WIDTH;",
        body,
        "",
        "    // debug taps: unconnected in this export (the per-stage streams",
        "    // live inside fft_sdf; probe there when needed)",
        "    assign dbg_stage_re = {(NUM_POINTS * INTERN_WIDTH){1'b0}};",
        "    assign dbg_stage_im = {(NUM_POINTS * INTERN_WIDTH){1'b0}};",
        "",
        "endmodule",
        "",
        "`default_nettype wire",
        "",
    ])


# ----------------------------------------------------------------------
# human-readable artifacts
# ----------------------------------------------------------------------

def twiddle_map_txt(cfg: FFTConfig) -> str:
    """Twiddle quantization contract: layout, rule, and every ROM word."""
    from twiddles import canonical_twiddles
    N = cfg.num_points
    td = cfg.twiddle_decimal
    tw = canonical_twiddles(N, cfg.twiddle_width, td, cfg.inverse)
    out = []
    out.append("twiddle_map.txt -- twiddle ROM contract (generated)")
    out.append("=" * 60)
    out.append(f"N={N}  inverse={int(cfg.inverse)}  ssr={cfg.ssr}  "
               f"width={cfg.twiddle_width}  Q{td}")
    out.append("")
    out.append("quantization: sat(round_half_up(2^%d * cos/sin)) clamped to" % td)
    out.append("  signed %d-bit range [-2^%d, 2^%d-1]; the identity W=1 maps"
               % (cfg.twiddle_width, cfg.twiddle_width - 1,
                  cfg.twiddle_width - 1))
    out.append("  to 131071 (one LSB below full scale) consistently in RTL")
    out.append("  ROM and golden model.")
    out.append("")
    out.append("ROM word format: hex, {re, im} packed MSB:LSB, %d bits/word."
               % (2 * cfg.twiddle_width))
    out.append("")
    if cfg.ssr == 1:
        dit = cfg.is_dit
        out.append("stage layout (fft_sdf.v TWIDDLE_FILE, one N-word table):")
        base = 0
        for s in range(cfg.num_stages):
            if dit:
                D = 1 << s
                idxs = [(j << (cfg.num_stages - s - 1)) % N for j in range(D)]
                stride = N >> (s + 1)
            else:
                D = N >> (s + 1)
                idxs = [(i << s) % N for i in range(D)]
                stride = 1 << s
            out.append(f"  stage {s}: rows [{base}..{base + D - 1}], "
                       f"D={D}, k = i*{stride}" +
                       (" (DIT)" if dit else " (DIF)"))
            base += D
        out.append("")
        out.append("entries (idx = ROM address, k = exp of W_N^k):")
        out.append("idx  k      re_float      im_float      re_int   im_int")
        base = 0
        for s in range(cfg.num_stages):
            if dit:
                D = 1 << s
                idxs = [(j << (cfg.num_stages - s - 1)) % N for j in range(D)]
            else:
                D = N >> (s + 1)
                idxs = [(i << s) % N for i in range(D)]
            out.append(f"-- stage {s} --")
            for j, k in enumerate(idxs):
                re, im = tw[k]
                import math
                ang = -2 * math.pi * k / N
                if cfg.inverse:
                    ang = -ang
                out.append(f"{base + j:4d}  {k:5d}  {math.cos(ang):+.6f}  "
                           f"{math.sin(ang):+.6f}  {re:8d} {im:8d}")
            base += D
    else:
        R, M = cfg.ssr, cfg.num_points // cfg.ssr
        out.append("crossbar WN table (fft_wn.mem): row r holds W_N^{r*p},")
        out.append(f"  p in [0,{M}); {R*M} words total.")
        out.append("")
        out.append("word  r  p      k      re_int   im_int")
        w = 0
        for r in range(R):
            for p in range(M):
                k = (r * p) % N
                re, im = tw[k]
                out.append(f"{w:5d}  {r}  {p:3d}  {k:5d}  {re:8d} {im:8d}")
                w += 1
    return "\n".join(out) + "\n"


def params_txt(cfg: FFTConfig, extra: dict) -> str:
    """Human-readable record of the chosen parameters."""
    iw = intern_width(cfg)
    lines = [
        f"core                = {'fft_ssr' if cfg.ssr > 1 else 'fft_sdf'}",
        f"num_points          = {cfg.num_points}",
        f"ssr                 = {cfg.ssr}",
        f"inverse             = {int(cfg.inverse)}",
        f"input_order         = {cfg.input_order}",
        f"output_order        = {cfg.output_order}",
        f"topology            = {'DIT' if cfg.is_dit else 'DIF'}",
        f"reorder_out         = {int(reorder_out(cfg))}",
        f"num_stages          = {cfg.num_stages}",
        f"pipe_depth          = 10                    (NLAYERS)",
        f"sample_width        = {cfg.sample_width}",
        f"sample_decimal      = {cfg.sample_decimal}",
        f"output_width        = {cfg.output_width}",
        f"output_decimal      = {cfg.output_decimal}",
        f"twiddle_width       = {cfg.twiddle_width}",
        f"twiddle_decimal     = {cfg.twiddle_decimal}",
        f"intern_width        = {iw}",
        f"scaling             = {cfg.scaling if cfg.scaling != 'auto' else 'auto'}",
        f"scaling_shifts      = {list(cfg.shifts)}",
        f"scaling_guaranteed  = {int(cfg.scaling_guaranteed)}",
        f"scaling_pack        = 32'h{scaling_pack(cfg):08x}",
        f"rounding            = round-half-up at scaling shifts; one fused",
        "                      round at twiddle_decimal+sigma on products",
        f"latency_cycles      = {extra['latency']}",
        f"throughput          = 1 frame / {extra['frames_per_clock_den']}"
        " clocks (ce high)",
        f"dsp_estimate        = {extra['dsp']}",
        f"preload_bits        = {extra['preload_bits']}",
        "",
        "memory styles (doc/mem_cutoffs.md cutoffs:",
        "  <=1024 bits distributed; <262144 block; else ultra):",
    ]
    if cfg.ssr == 1:
        for s in range(cfg.num_stages):
            D = (1 << s) if cfg.is_dit else (cfg.num_points >> (s + 1))
            bits = 2 * D * cfg.sample_width
            style = mem_style_bits(bits)
            lines.append(f"  stage {s:2d}: delay/pfifo {2 * D:5d} x "
                         f"{cfg.sample_width:2d}b = {bits:7d} bits -> {style}")
        rbits = 2 * cfg.num_points * cfg.output_width
        if reorder_out(cfg):
            lines.append(f"  reorder   : {2 * cfg.num_points:5d} x "
                         f"{cfg.output_width:2d}b = {rbits:7d} bits -> "
                         f"{mem_style_bits(rbits)}")
    else:
        lc = lane_cfg(cfg)
        for s in range(lc.num_stages):
            D = lc.num_points >> (s + 1)
            bits = 2 * D * cfg.sample_width
            lines.append(f"  lane st{s:2d}: {2 * D:5d} x {cfg.sample_width:2d}b"
                         f" = {bits:7d} bits -> {mem_style_bits(bits)}"
                         f"  (x{cfg.ssr} lanes)")
        rbits = 2 * lc.num_points * cfg.output_width
        lines.append(f"  lane reorder: {2 * lc.num_points:5d} x "
                     f"{cfg.output_width:2d}b = {rbits:7d} bits -> "
                     f"{mem_style_bits(rbits)}  (x{cfg.ssr} lanes)")
    return "\n".join(lines) + "\n"


def readme_txt(cfg: FFTConfig, args) -> str:
    ssr = cfg.ssr > 1
    top = "fft_ssr" if ssr else "fft_top"
    files = (([] if ssr else ["fft_core.v"]) + core_files(cfg))
    srcs = " ".join(files)
    tbname = "tb_fft_ssr.cpp" if ssr else "tb_fft_sdf.cpp"
    gargs = ""
    if ssr:
        gargs = (" \\\n  -GNUM_POINTS=%d -GSSR=%d \\\n  -GSCALING_PACK=32'h%08x"
                 " -GINTERN_WIDTH=%d -GINVERSE=%d -GPIPE_DEPTH=10"
                 % (cfg.num_points, cfg.ssr, scaling_pack(engine_cfg(cfg)),
                    intern_width(lane_cfg(cfg)), int(cfg.inverse)))
    lines = [
        "fftgen exported core -- README (generated)",
        "=" * 50,
        "",
        "Configuration: see params.txt; machine-readable: fft_params.vh.",
        "Numerical contract per ROM word: see twiddle_map.txt.",
        "",
        "Contents:",
        "  fft_core.v        generated top (R=1 only; replaces the repo's",
        "                    generic fft_top.v -- parameters baked in)",
        "  fft_sdf.v         radix-2 SDF stage chain (10-layer pipeline)",
        "  fft_reorder.v     ping-pong bit-reversal reorder",
        "  fft_cross.v       SSR cross-lane combine (SSR builds)",
        "  fft_ssr.v         SSR top: R lane engines + crossbar (SSR builds)",
        "  fft_top.v         generic parameter wrapper (SSR builds; lanes)",
        "  fft_twiddles.mem  twiddle ROM ($readmemh)",
        "  fft_preloads.vh   post-warm FSM preload pack (74 bits/stage)",
        "  fft_params.vh     concrete parameters as `define macros",
        "  params.txt        human-readable parameter record",
        "  twiddle_map.txt   twiddle layout + quantization contract",
        "  tb/               Verilator testbench (C++)",
        "  stimulus.txt      input vectors (hex re im user last)",
        "  expected.txt      golden-model expected output",
        "  vivado/synth.tcl  OOC synthesis script (IMP=1 adds P&R)",
        "  vivado/timing.xdc clock constraint",
        "",
        "Simulation (Verilator), from THIS directory:",
        "",
        f"  verilator --cc --exe --build -j 4 --top-module {top} \\",
        "    -Wno-fatal +define+FFTGEN_PRELOADS +incdir+. \\",
        f"    -CFLAGS \"-DTB_SAMPLE_WIDTH={cfg.sample_width} "
        f"-DTB_OUTPUT_WIDTH={cfg.output_width}"
        + (f" -DTB_SSR={cfg.ssr}" if ssr else "") + "\" \\",
    ]
    if ssr:
        lines.append("    " + gargs.replace(" \\\n  ", " \\\n    "))
    lines += [
        f"    {srcs} tb/{tbname}",
        "    ./obj_dir/V%s      # writes actual.txt" %
        ("ssr" if ssr else "top"),
        "",
        "expected.txt vs actual.txt: bit-exact for R=1; SSR compares with",
        "tolerance R/2+1 LSB after word-offset alignment (lane-0 identity",
        "twiddle differs from the golden 131071-multiply by <1 LSB).",
        "",
        "Synthesis:",
        "",
        "  cd vivado && <vivado> -mode batch -source synth.tcl \\",
        f"      -tclargs {args.part} {args.clk_mhz}",
        "  Set IMP=1 in synth.tcl (or pass as 3rd arg) for place & route.",
        "",
    ]
    return "\n".join(lines)


def synth_tcl(cfg: FFTConfig, part: str, clk_mhz: float) -> str:
    ssr = cfg.ssr > 1
    top = "fft_ssr" if ssr else "fft_top"
    # fft_core.v (generated wrapper) leads so its fft_preloads.vh include
    # is parsed before fft_sdf.v regardless of tool define semantics
    files = (([] if ssr else ["fft_core.v"]) + core_files(cfg))
    srcs = " \\\n".join(f"    [file join $rtl_dir {f}]" for f in files)
    mems = ["fft_twiddles.mem"] + (
        ["fft_twiddles_lane.mem", "fft_wn.mem"] if ssr else [])
    mem_copy = "\n".join(
        f'file copy -force [file join $rtl_dir "{m}"] .' for m in mems)
    generics = ""
    if ssr:
        generics = (
            "synth_design -top fft_ssr -generic NUM_POINTS=%d \\\n"
            "    -generic SSR=%d -generic SCALING_PACK=32'h%08x \\\n"
            "    -generic INTERN_WIDTH=%d -generic INVERSE=%d \\\n"
            "    -generic PIPE_DEPTH=10 \\\n"
            "    -generic WN_FILE=\"fft_wn.mem\" \\\n"
            "    -generic TWIDDLE_FILE=\"fft_twiddles_lane.mem\""
            % (cfg.num_points, cfg.ssr, scaling_pack(engine_cfg(cfg)),
               intern_width(engine_cfg(cfg)), int(cfg.inverse)))
    else:
        generics = "synth_design -top fft_top"
    return """\
# OOC synthesis (and optional implementation) for the exported FFT core.
# usage: vivado -mode batch -source synth.tcl -tclargs <part> <clk_mhz> [IMP]
# Run from the vivado/ subdirectory of the export.
set part   [lindex $argv 0]
set clk_mhz [lindex $argv 1]
set IMP    [expr {[llength $argv] > 2 ? [lindex $argv 2] : 0}]
set rtl_dir [file normalize [file join [file dirname [info script]] ..]]

set period_ns [expr {1000.0 / $clk_mhz}]

# $readmemh resolves relative to the run directory: bring the ROMs here.
""" + mem_copy + """

create_project -in_memory -part $part
add_files -fileset sources_1 [list \\
""" + srcs + """
]
set_property top """ + top + """ [current_fileset]
set_property verilog_define {FFTGEN_PRELOADS=1} [current_fileset]
set_property include_dirs [list $rtl_dir ..] [current_fileset]

""" + generics + """
create_clock -period $period_ns -name clk [get_ports clk]

report_utilization -file utilization.rpt
report_timing_summary -delay_type max -max_paths 10 -file timing.rpt

if {$IMP} {
    opt_design
    place_design
    phys_opt_design
    route_design
    report_utilization -file utilization_impl.rpt
    report_timing_summary -delay_type max -max_paths 10 -file timing_impl.rpt
}
"""


def timing_xdc(clk_mhz: float) -> str:
    period = 1000.0 / clk_mhz
    return ("# primary clock constraint (exported)\n"
            "create_clock -period %.3f -name clk [get_ports clk]\n"
            % period)


# ----------------------------------------------------------------------
# verification vectors (stimulus + golden expected)
# ----------------------------------------------------------------------

def write_tb_vectors(cfg: FFTConfig, outdir: str, num_frames: int,
                     seed: int) -> None:
    """stimulus.txt / expected.txt exactly as the test-suite flow writes
    them (fft_gen.generate / generate_ssr semantics)."""
    import random
    from stimuli import random_frame
    from golden import OrderedFFTModel

    def markers(n_pts, frames):
        return [(1 if j == 0 else 0, 1 if j == n_pts - 1 else 0)
                for _ in range(frames) for j in range(n_pts)]

    rng = random.Random(seed)
    N = cfg.num_points
    frames = [random_frame(N, cfg.sample_width, rng) for _ in range(num_frames)]

    if cfg.ssr > 1:
        from golden_ssr import SSRGoldenModel
        # pad frames let the pipeline fill before emission syncs -- same
        # arithmetic as fft_gen.generate_ssr so the vectors match 1:1
        M = N // cfg.ssr
        probe = SSRGoldenModel(cfg)
        pad = (probe.latency + M - 1) // M + 2
        frames += [random_frame(N, cfg.sample_width, rng)
                   for _ in range(pad)]
        samples = [s for fr in frames for s in fr]
        mk = []
        for _ in range(len(frames)):
            mk += [(1, 0)] + [(0, 0)] * (N - 2) + [(0, 1)]
        with open(os.path.join(outdir, "stimulus.txt"), "w") as f:
            for (re_, im_), (u, l) in zip(samples, mk):
                f.write("%s %s %d %d\n" % (_hexw(re_, cfg.sample_width),
                                           _hexw(im_, cfg.sample_width), u, l))
        got = probe.process_stream(samples, markers=mk)
        exp_path = os.path.join(outdir, "expected.txt")
    else:
        samples = [s for fr in frames for s in fr]
        if cfg.is_dit:
            br = [int(format(k, "0%db" % cfg.num_stages)[::-1], 2)
                  for k in range(N)]
            samples = [fr[br[j]] for fr in frames for j in range(N)]
        mk = markers(N, num_frames)
        with open(os.path.join(outdir, "stimulus.txt"), "w") as f:
            for (re_, im_), (u, l) in zip(samples, mk):
                f.write("%s %s %d %d\n" % (_hexw(re_, cfg.sample_width),
                                           _hexw(im_, cfg.sample_width), u, l))
        m = OrderedFFTModel(cfg)
        got = m.process_stream(samples, markers=mk)
        exp_path = os.path.join(outdir, "expected.txt")

    with open(exp_path, "w") as f:
        for row in got:
            f.write("%d %d %d %d\n" % (row[0], row[1], row[2], row[3]))


def _hexw(v: int, width: int) -> str:
    return format(v & ((1 << width) - 1), "0%dx" % ((width + 3) // 4))


# ----------------------------------------------------------------------
# export driver
# ----------------------------------------------------------------------

def export(cfg: FFTConfig, args) -> dict:
    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)
    os.makedirs(os.path.join(outdir, "vivado"), exist_ok=True)
    written = []

    # RTL sources
    for fn in core_files(cfg):
        shutil.copy(os.path.join(RTL, fn), os.path.join(outdir, fn))
        written.append(fn)

    # twiddle ROM contents
    from fft_gen import (write_twiddle_mem, write_lane_twiddle_mem,
                         write_wn_mem, write_preload_pack_vh)
    write_twiddle_mem(cfg, os.path.join(outdir, "fft_twiddles.mem"))
    written.append("fft_twiddles.mem")
    if cfg.ssr > 1:
        lc = lane_cfg(cfg)
        write_lane_twiddle_mem(lc, os.path.join(outdir,
                                                "fft_twiddles_lane.mem"))
        write_wn_mem(cfg, os.path.join(outdir, "fft_wn.mem"))
        written += ["fft_twiddles_lane.mem", "fft_wn.mem"]

    # post-warm FSM preload pack (single source: golden stage_preloads)
    import dataclasses
    from golden import SDFGoldenModel
    if cfg.ssr > 1:
        lc = lane_cfg(cfg)
        lc.input_order = "native"
        lc.output_order = "bitreversed"
        gm = SDFGoldenModel(lc, dit=False)
    else:
        nat_in, nat_out = (("bitreversed", "native") if cfg.is_dit
                           else ("native", "bitreversed"))
        gm = SDFGoldenModel(dataclasses.replace(
            cfg, input_order=nat_in, output_order=nat_out), dit=cfg.is_dit)
    nbits = write_preload_pack_vh(gm.stage_preloads,
                                  os.path.join(outdir, "fft_preloads.vh"))
    written.append("fft_preloads.vh")

    # generated wrapper (R=1 only; SSR keeps documented -G generics)
    if cfg.ssr == 1:
        with open(os.path.join(outdir, "fft_core.v"), "w") as f:
            f.write(core_wrapper_r1(cfg))
        written.append("fft_core.v")
    else:
        # SSR needs the GENERIC fft_top (instantiated per lane by fft_ssr)
        shutil.copy(os.path.join(RTL, "fft_top.v"),
                    os.path.join(outdir, "fft_top.v"))
        if "fft_top.v" not in written:
            written.append("fft_top.v")

    # records
    with open(os.path.join(outdir, "fft_params.vh"), "w") as f:
        f.write(params_header(cfg))
    written.append("fft_params.vh")

    extra = {}
    extra["latency"] = latency_cycles(cfg)
    extra["frames_per_clock_den"] = cfg.num_points // cfg.ssr
    if cfg.ssr > 1:
        n_st = lane_cfg(cfg).num_stages
        extra["dsp"] = ("%d (R lanes x 4 x %d stages + crossbar network)"
                        % (cfg.ssr * 4 * n_st, n_st))
    else:
        extra["dsp"] = "%d (4 per stage)" % (4 * cfg.num_stages)
    extra["preload_bits"] = nbits
    with open(os.path.join(outdir, "params.txt"), "w") as f:
        f.write(params_txt(cfg, extra))
    written.append("params.txt")

    with open(os.path.join(outdir, "twiddle_map.txt"), "w") as f:
        f.write(twiddle_map_txt(cfg))
    written.append("twiddle_map.txt")

    # verification vectors + testbench
    if args.num_frames > 0:
        write_tb_vectors(cfg, outdir, args.num_frames, args.seed)
        written += ["stimulus.txt", "expected.txt"]
        os.makedirs(os.path.join(outdir, "tb"), exist_ok=True)
        tbname = "tb_fft_ssr.cpp" if cfg.ssr > 1 else "tb_fft_sdf.cpp"
        shutil.copy(os.path.join(TB, tbname),
                    os.path.join(outdir, "tb", tbname))
        written.append("tb/" + tbname)

    # vivado scripts
    with open(os.path.join(outdir, "vivado", "synth.tcl"), "w") as f:
        f.write(synth_tcl(cfg, args.part, args.clk_mhz))
    with open(os.path.join(outdir, "vivado", "timing.xdc"), "w") as f:
        f.write(timing_xdc(args.clk_mhz))
    written += ["vivado/synth.tcl", "vivado/timing.xdc"]

    with open(os.path.join(outdir, "README.txt"), "w") as f:
        f.write(readme_txt(cfg, args))
    written.append("README.txt")

    return {"outdir": outdir, "files": written}


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--num-points", type=int, required=True,
                    help="N, power of two (>= 2)")
    ap.add_argument("--ssr", type=int, default=1,
                    help="samples per clock, power of two dividing N")
    ap.add_argument("--inverse", action="store_true", help="IFFT")
    ap.add_argument("--input-order", default="native",
                    choices=["native", "bitreversed"])
    ap.add_argument("--output-order", default=None,
                    choices=["native", "bitreversed"],
                    help="default: bitreversed (DIF core convention)")
    ap.add_argument("--sample-width", type=int, default=16)
    ap.add_argument("--sample-decimal", type=int, default=0)
    ap.add_argument("--output-width", type=int, default=None,
                    help="defaults to sample-width")
    ap.add_argument("--output-decimal", type=int, default=None,
                    help="defaults to sample-decimal")
    ap.add_argument("--twiddle-width", type=int, default=18)
    ap.add_argument("--scaling", default="auto",
                    help="'auto' or comma-separated per-stage shifts 0..2")
    ap.add_argument("--num-frames", type=int, default=3,
                    help="verification frames to emit (0 skips the TB)")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--part", default="xcku5p-ffva676-1-e")
    ap.add_argument("--clk-mhz", type=float, default=500.0)
    ap.add_argument("--outdir", default=os.path.join("build", "export"))
    args = ap.parse_args(argv)
    if args.output_order is None:
        args.output_order = "bitreversed"

    try:
        cfg = build_config(args)
    except ValueError as e:
        print("error: %s" % e, file=sys.stderr)
        return 2
    res = export(cfg, args)
    print("Exported %s to %s/" % (
        "SSR%d" % cfg.ssr if cfg.ssr > 1 else "R=1", res["outdir"]))
    for name in res["files"]:
        print("  %s" % name)
    print("\nSee README.txt for simulation and synthesis commands.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
